'use client'
import Header from "@/components/header/Header";
import "./globals.css";
import Slider from "@/components/slider/Slider";
import CardComponents from "@/components/card/CardComponents";
import Footer from "@/components/footer/Footer";
import Project from "@/components/project/Project";

export const metadata = {
  title: "Unico It Ltd",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      {/*Header*/}
      <Header></Header>
      {/*slider*/}
      <Slider></Slider>
      <CardComponents></CardComponents>
      <Project></Project>

        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
